version: '3.8'

services:
  # Сервис для бэкенда (Flask)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - ./database.db:/app/backend/database.db
      - ./logs:/app/logs
    ports:
      - "5000:5000"
    restart: always


  # Сервис для фронтенда (Svelte в продакшн-режиме через Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  backend_data: